### ISSUE TITLE
bug: missingdocker labels for `proksi.plugins.oauth2` breaks docker discovery process

### ISSUE THREAD

**Issue by luizfonseca** [luizfonseca/proksi#23]
## How to Replicate

Forget to set any of the `proksi.plugins.oauth2.*` labels:

```yaml
        proksi.enabled: "true"
        proksi.host: "subdomain.domain.com"
        proksi.port: "9001"

        proksi.plugins.oauth2.provider: "github"
        proksi.plugins.oauth2.client_id: "${GITHUB_OAUTH_CLIENT_ID:-notSet}"
        proksi.plugins.oauth2.client_secret: "${GITHUB_OAUTH_CLIENT_SECRET:-notSet}"
        # JWT_SECRET is required, but not providing it breaks the docker label service
        # proksi.plugins.oauth2.jwt_secret: "${GITHUB_MIDDLEWARE_JWT_SECRET_KEY:-notSet}"
        proksi.plugins.oauth2.validations: |
          [ {  "type": "email", "value": "${GITHUB_EMAIL:-notSet}" } ]

```

Proksi process breaks with: 
```
2024-06-08 18:35:21 called `Option::unwrap()` on a `None` value
```
