### ISSUE TITLE
Docker swarm example with config

### ISSUE THREAD

**Issue by bgervan** [luizfonseca/proksi#35]
Hi, 

I wanted to check the performance with the docker compose example, but it misses the configuration file. 
Can you provide a full example with config and compose?

**Comment by luizfonseca** [comment]
Hey @bgervan, of course! Let's take an example where I have 1 docker service exposed through `swarm` or through just a `docker compose up` setup:

If you are only using docker, you probably don't even need the config file -- just labels and environment variables.


TL;DR:
- If you are running `docker compose up`, `labels` are at the same level or ports/image etc
- If you are running `swarm mode`, update to `PROKSI_DOCKER__MODE: "swarm"` and move the `labels` to be inside the `deploy:` key.

## Docker compose

The important piece here is that via `docker compose` your **container** labels are not part of the `deploy:` key, so you have to put the labels in the same level as image/ports etc:

```yaml
networks:
  public:
    name: public 
    external: true
 
 # Proksi
 proksi:
    image: luizfonseca/proksi:latest
    environment:
      PROKSI_LOGGING__LEVEL: "info" # change to `debug` if you want more logging
      PROKSI_WORKER_THREADS: 4 # this only applies for the :443 port
 
      # Docker
      PROKSI_DOCKER__ENABLED: "true"
      PROKSI_DOCKER__MODE: "compose"

      # Lets Encrypt 
      PROKSI_LETS_ENCRYPT__ENABLED: "true"
      PROKSI_LETS_ENCRYPT__STAGING: "true" # If you want real certs, change to "false"
      PROKSI_LETS_ENCRYPT__EMAIL: "contact@your-email.com"
      PROKSI_PATHS__LETS_ENCRYPT: "/app/data/letsencrypt" # volume for your certs
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # before: create this folder `data` with `mkdir ./data` (or any other folder)
      - ./data/letsencrypt:/app/data/letsencrypt # this is important, we save certs here
      - /var/run/docker.sock:/var/run/docker.sock # how we get containers
    networks:
      - public


  # Example webserver
  nginx-demo:
    image: nginxdemos/hello

    networks:
      - public
    labels:
      proksi.enabled: "true"
      proksi.host: "nginx-demo.localhost" # update your /etc/hosts if possible
      proksi.port: "80" 

      # IMPORTANT: if you don't actually have a real domain, use this to get LOCAL certs.
      proksi.ssl_certificate.self_signed_on_failure: "true"

      # Optional path matching
      # proksi.match_with.path.pattern.any: "/*" 
    deploy:
      replicas: 2 # Proksi will automatically load-balance between replicas
```


## Docker swarm

Simply move the `labels:` piece inside the `deploy:` key, like so:

```yaml
  # Example webserver
  nginx-demo:
    image: nginxdemos/hello

    networks:
      - public
    
    deploy:
      replicas: 2 # Proksi will automatically load-balance between replicas
      labels:
        proksi.enabled: "true"
        proksi.host: "nginx-demo.localhost" # update your /etc/hosts if possible
        proksi.port: "80" 
        
        # IMPORTANT: if you don't actually have a real domain, use this to get LOCAL certs.
        proksi.ssl_certificate.self_signed_on_failure: "true"
```

and change the environment variable on **proksi:** to be `PROKSI_DOCKER__MODE: "swarm"`. The rest stays the same.

**Comment by luizfonseca** [comment]
Btw, if you are running on a mac, it's unlikely you will get good performance because the Unix environment is virtualized, but you should get around 30K~60K req/s give or take.

If you are testing on a linux host, then you should get a close result around 80~100K req/s and upwards (depending on what you are running of course)

**Comment by bgervan** [comment]
Thanks for the quick reply. 
Modified a bit, the compose mode doesn't exist. 

```
networks:
  web:
    name: web
    # external: true

services:
  # Proksi
  proksi:
    image: luizfonseca/proksi:latest
    logging:
      driver: none
    environment:
      PROKSI_LOGGING__LEVEL: "INFO" # change to `debug` if you want more logging
      PROKSI_LOGGING__ACCESS_LOGS_ENABLED: "false"
      PROKSI_WORKER_THREADS: 4 # this only applies for the :443 port

      # Docker
      PROKSI_DOCKER__ENABLED: "true"
      PROKSI_DOCKER__MODE: "container"

      # Lets Encrypt
      PROKSI_LETS_ENCRYPT__ENABLED: "true"
      PROKSI_LETS_ENCRYPT__STAGING: "true" # If you want real certs, change to "false"
      PROKSI_LETS_ENCRYPT__EMAIL: "contact@your-email.com"
      PROKSI_PATHS__LETS_ENCRYPT: "/app/data/letsencrypt" # volume for your certs
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # before: create this folder `data` with `mkdir ./data` (or any other folder)
      - ./data/letsencrypt:/app/data/letsencrypt # this is important, we save certs here
      - /var/run/docker.sock:/var/run/docker.sock # how we get container info
    networks:
      - web


  # Example webserver
  nginx-demo:
    image: nginxdemos/hello

    networks:
      - web
    labels:
      proksi.enabled: "true"
      proksi.host: "nginx-demo.localhost" # update your /etc/hosts if possible
      proksi.port: "80"

      # IMPORTANT: if you don't actually have a real domain, use this to get LOCAL certs.
      proksi.ssl_certificate.self_signed_on_failure: "true"

      # Optional path matching
      # proksi.match_with.path.pattern.any: "/*"
    deploy:
      replicas: 2 # Proksi will automatically load-balance between replicas

```

If I disable logging, I got 10-12K/s, which is great, considering I got 6-8K with traefik and nginx on the same VPS. 
`docker compose up --attach nginx-demo`

Tried to disable access logs, but PROKSI_LOGGING__ACCESS_LOGS_ENABLED: "false" doesn't seem to work and the logs affect the result heavily. (7k/s)
