### ISSUE TITLE
[QUESTION] How to config reverse proxy for domain?

### ISSUE THREAD

**Issue by adammakowskidev** [luizfonseca/proksi#38]
Hi @luizfonseca 
I am wondering how I can create a proxy for a domain and use cache? I want build small CDN. Can you provide some example? The documentation is small
In nginx I do it this way

```
proxy_cache_path /var/local/cache/domain_net keys_zone=domain_net:10m inactive=1y;


server {
    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 80;
    http2 on;
    http3 on;
    server_name cdn.domain.com;

    # SSL location
    ssl_certificate /var/local/certificate.pem;
    ssl_certificate_key /var/local/private.key;
 
    # SSL settings
    ssl_protocols TLSv1.3 TLSv1.2;
    ssl_early_data on;
    ssl_session_tickets on;
    
    # http3/quic settings
    http3_stream_buffer_size 1m;

    # global website headers
    add_header Alt-Svc 'h3=":443"; ma=86400';
    add_header Cache-Status $upstream_cache_status;

    # proxy CDN cache settings
    location / {
        proxy_set_header Early-Data $ssl_early_data;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Access-Control-Allow-Origin *;
        proxy_set_header "Connection" "";
        proxy_cache domain_net;
        proxy_cache_valid any 1d;
        proxy_pass https://domain.net;
    }
}
```

**Comment by luizfonseca** [comment]
Hey @adammakowskidev, thanks for the question!

Unfortunately I haven't yet implemented any caching logic/enablement, though I can do speed that up if it's of your interest. 

(_I haven't done that yet since I had other priorities in mind for my own use cases._)


In regards to the configuration, it looks like this currently:

```yaml
lets_encrypt: # If you don't certs from let's encrypt at all, just set it to `false`
  enabled: true
  email: "a-valid@email.com"

paths:
  lets_encrypt: "/var/local/" # make sure the path exists first and the process has access to it :)

routes:
  - host: cdn.domain.net
    upstreams:
      - ip: domain.net
        port: 443
    headers:
      add: 
        - name: "Access-Control-Allow-Origin"
          value: "*"
        - name: "Alt-Svc"
          value: |
            h3=":443"; ma=86400
        - name: "Cache-Status"
          value: "<value>"
        - name: "Cache-Control" # other headers if needed
          value: "max-age=84600"
```

So as you can see it's missing most of the things you need. That said, let me know if you have suggestions in regards to the configuration/caching you would like to see! 

It's not something I need at the moment but I will be happy to help you get that working in `proksi` and we can test it together.

The priority list for me looks like this (🟢 = easy, 🟢🟢 = medium, complex = 🟢🟢🟢):

1. Able to set certificate path per `host` (🟢)
2. Able to set Ssl protocols (🟢)
3. Able to set ssl tickets & early data (medium? Might need some testing) (🟢)
4. Able to pass on original headers to the given proxied host (🟢🟢)
5. Able to set a proxy cache path (and a expiration data) (🟢)
6. Able to direct the cache filter (state-while-revalidate, expiration keys, 304 etc) (🟢🟢🟢)

**Comment by adammakowskidev** [comment]
Hi. Thx for your help.
To multiple domains I can use more routes without problems?
Tinyufo cache looks very interesting. Will you work on it?

**Comment by luizfonseca** [comment]
>  To multiple domains I can use more routes without problems?
Yep, 

```yaml
routes:
  - host: cdn.domain.net
    ssl_certificate:
      # good if you are testing locally, so you don't need to deploy it beforehand
      self_signed_on_failure: true
    upstreams:
      - ip: sub1.domain.net
        port: 443
      - ip: sub2.domain.net
        port: 443
  - host: cdn-2.domain.net
    # ... and so on
  - host: ...
```


> Tinyufo cache looks very interesting. Will you work on it?
I will start working on the cache implementation right away -- would you mind helping me test things out during the process?

**Comment by adammakowskidev** [comment]
Ups. I meant multiple hosts with different upstreams
If I can do some tests, I'll be happy to do so.

**Comment by luizfonseca** [comment]
>Ups. I meant multiple hosts with different upstreams

If i understood correctly yeah, multiple hosts + multiple upstreams are supported. The important bit here is that is always this shape:

```yaml

routes:
  - host: ...
    upstreams:
     - ip: ...
       port: ...
    (...extraOptions)

  - host: ...
    upstreams:
     - ip: ...
       port: ...
    (...extraOptions)
```

and you can create as many as you want (I haven't tested with more than 30 hosts so far, so let me know if you see any issues)
